#!/usr/bin/env python3
"""Build the static model-token inventory used to audit CMU39 projection."""

from __future__ import annotations

import json
import sys
from pathlib import Path
from pprint import pformat

import sentencepiece as spm
from transformers import Wav2Vec2Processor


REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from src.core.cmu39_projection import project_ipa_to_cmu39  # noqa: E402
from src.core.ipa_utils import ARPABET_TO_IPA  # noqa: E402


W2V2_REPOS = {
    "ctag": "ctaguchi/wav2vec2-large-xlsr-japlmthufielta-ipa1000-ns",
    "lv60": "facebook/wav2vec2-lv-60-espeak-cv-ft",
    "xlsr53": "facebook/wav2vec2-xlsr-53-espeak-cv-ft",
}
ZIPA_MODEL = REPO_ROOT / "src/model/zipa/resources/unigram_127.model"
BABAR_VOCAB = REPO_ROOT / "exp/download/babar/vocab-phoneme-tinyvox.json"
OUTPUT = REPO_ROOT / "src/core/cmu39_model_vocab.py"


def _w2v2_tokens(repo: str) -> tuple[str, ...]:
    processor = Wav2Vec2Processor.from_pretrained(repo, local_files_only=True)
    vocab = processor.tokenizer.get_vocab()
    return tuple(sorted(vocab, key=lambda token: (vocab[token], token)))


def _zipa_tokens() -> tuple[str, ...]:
    processor = spm.SentencePieceProcessor()
    processor.load(str(ZIPA_MODEL))
    return tuple(processor.IdToPiece(i) for i in range(processor.GetPieceSize()))


def _babar_tokens() -> tuple[str, ...]:
    vocab = json.loads(BABAR_VOCAB.read_text(encoding="utf-8"))
    return tuple(sorted(vocab, key=lambda token: (vocab[token], token)))


def _huper_tokens() -> tuple[str, ...]:
    return tuple(sorted(set(ARPABET_TO_IPA.values())))


def build_sources() -> dict[str, tuple[str, ...]]:
    sources = {name: _w2v2_tokens(repo) for name, repo in W2V2_REPOS.items()}
    zipa_tokens = _zipa_tokens()
    sources["zipactc"] = zipa_tokens
    sources["zipactc_ns"] = zipa_tokens
    sources["babar"] = _babar_tokens()
    sources["huper"] = _huper_tokens()
    return sources


def _project_token(token: str) -> tuple[str, ...]:
    projected = project_ipa_to_cmu39(token, token)
    return tuple(projected.split()) if projected else ()


def main() -> None:
    sources = build_sources()
    token_set = sorted(set().union(*sources.values()))
    dropped = tuple(token for token in token_set if not _project_token(token))
    mapped = {
        token: _project_token(token)
        for token in token_set
        if _project_token(token)
    }

    content = '''"""Static decoded-token inventory for CMU39 projection audits.

Generated by scripts/build_cmu39_model_vocab.py.
"""

from __future__ import annotations

from typing import Dict, FrozenSet, Tuple


MODEL_VOCAB_TOKENS_BY_SOURCE: Dict[str, Tuple[str, ...]] = {sources}

MODEL_VOCAB_TOKEN_SET: FrozenSet[str] = frozenset(
    token
    for tokens in MODEL_VOCAB_TOKENS_BY_SOURCE.values()
    for token in tokens
)

DROPPED_MODEL_VOCAB_TOKENS: FrozenSet[str] = frozenset({dropped})

MODEL_VOCAB_TO_CMU39: Dict[str, Tuple[str, ...]] = {mapped}
'''.format(
        sources=pformat(sources, width=88, sort_dicts=True),
        dropped=pformat(dropped, width=88, sort_dicts=True),
        mapped=pformat(mapped, width=88, sort_dicts=True),
    )
    OUTPUT.write_text(content, encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(REPO_ROOT)}")
    print(f"Unique tokens: {len(token_set)}")
    print(f"Mapped tokens: {len(mapped)}")
    print(f"Dropped tokens: {len(dropped)}")


if __name__ == "__main__":
    main()
